name: ecommerce-store
namespace: ecommerce
replicas: 1
image: ddncr.azurecr.io/ecommerce-store:latest
containerPort: 3001
service:
  portname: http
  port: 3001
  targetPort: 3001

env:
  - name: NEXT_PUBLIC_API_URL
    value: "http://4.157.222.170:3000/api/7db58050-e513-4f4a-a4b4-635320c21b0a"
